language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

env:
    - DEPS=no

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - if [ "$DEPS" == "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
    - if [ "$DEPS" == "no" ]; then composer install; fi;

script: |
    ./vendor/bin/psalm
    ./vendor/bin/phpunit
matrix:
    include:
        - php: 8.0
    fast_finish: true
